services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: pass

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: